"use client";

import { useState } from "react";

type Screen = "Home" | "Property" | "Assets" | "Records" | "Service";

const homes = [
  { id: "home", name: "Your Home", line: "Colorado Springs, CO · primary demo", health: 82 },
  { id: "cedar", name: "Cedar Ridge", line: "Colorado Springs, CO · sample", health: 91 },
  { id: "monument", name: "Monument Park", line: "Colorado Springs, CO · sample condo", health: 76 },
];
const assets = [
  ["Roof system", "Envelope", "9 years", 88, "Good", "Inspection photos and warranty on file"],
  ["Furnace + A/C", "HVAC", "12 years", 71, "Watch", "Annual service due in 30 days"],
  ["Water heater", "Plumbing", "8 years", 68, "Action soon", "Flush history needs verification"],
  ["Electrical panel", "Electrical", "18 years", 93, "Good", "Panel label verified"],
];

function Status({ children }: { children: string }) { return <span className={`status ${children === "Good" ? "good" : children === "Watch" ? "watch" : "soon"}`}>{children}</span>; }
function Score({ score, title, note }: { score:number; title:string; note:string }) { return <div className="score" style={{background:`conic-gradient(#2e8b68 ${score*3.6}deg,#e6efed 0deg)`}}><div><b>{score}</b><span>{title}</span><small>{note}</small></div></div>; }

export default function App() {
  const [screen, setScreen] = useState<Screen>("Home"); const [homeId,setHomeId]=useState("home"); const [openHomes,setOpenHomes]=useState(false); const [asset,setAsset]=useState(1); const [issue,setIssue]=useState(false);
  const home=homes.find(h=>h.id===homeId) ?? homes[0];
  const go=(next:Screen)=>setScreen(next);
  return <main className="shell"><aside className="sidebar"><div className="brand"><i>H</i>Home<span>Ops</span></div><p className="side-label">PROPERTY WORKSPACE</p><button className="home-select" onClick={()=>setOpenHomes(!openHomes)}><i>{home.name.split(" ").map(x=>x[0]).join("")}</i><span><b>{home.name}</b><small>{home.line}</small></span><em>⌄</em></button>{openHomes&&<div className="home-menu">{homes.map(h=><button key={h.id} onClick={()=>{setHomeId(h.id);setOpenHomes(false)}}><b>{h.name}</b><small>{h.health} health</small></button>)}</div>}<nav>{(["Home","Property","Assets","Records","Service"] as Screen[]).map((n,i)=><button className={screen===n?"nav active":"nav"} onClick={()=>go(n)} key={n}><i>{["⌂","⌘","◈","▤","↗"][i]}</i>{n}</button>)}</nav><div className="side-bottom"><button onClick={()=>go("Service")}>✦ Ask HomeOps</button><small>Proof of concept · Demo data</small></div></aside><section className="main"><header><div><p className="eyebrow">HOMEOPS / {screen.toUpperCase()}</p><h1>{screen==="Home"?"Good afternoon, Joshua.":screen}</h1></div><div className="header-buttons"><button className="plain">Share record</button><button className="primary" onClick={()=>go("Service")}>+ Add / Request help</button><i>JS</i></div></header>{screen==="Home"&&<Home home={home} go={go} request={()=>{setIssue(true);go("Service")}}/>}{screen==="Property"&&<Property home={home} asset={asset} setAsset={setAsset}/>} {screen==="Assets"&&<Assets asset={asset} setAsset={setAsset}/>} {screen==="Records"&&<Records/>}{screen==="Service"&&<Service issue={issue}/>}</section></main>;
}

function Home({home,go,request}:{home:typeof homes[number];go:(s:Screen)=>void;request:()=>void}) { return <div className="home-grid"><section className="hero-card"><div><p className="eyebrow green-label">PRIMARY DEMO PROPERTY</p><h2>{home.name}</h2><p>{home.line}</p><div className="facts"><span>Built 2006</span><span>2,186 sq ft</span><span>4 bed · 3 bath</span></div><button className="plain" onClick={()=>go("Property")}>Open digital twin →</button></div><figure><img src="/dollhouse.png" alt="Roof-off 3D dollhouse property model"/><figcaption>Demo twin · replace with mirrored home model</figcaption></figure></section><section className="health-card"><div className="health-top"><Score score={home.health} title="Home Health" note="Good"/><div><h3>Healthy, with 2 items to plan.</h3><p>Overall condition is strong. Keep the maintenance rhythm and plan ahead for aging equipment.</p><button className="link" onClick={()=>go("Assets")}>See score drivers →</button></div></div><div className="metrics"><Metric value="79" label="Performance" note="↑ 3 this year"/><Metric value="74" label="Readiness" note="2 tasks due"/><Metric value="68%" label="Record complete" note="14 open items"/></div></section><section className="card priority"><Title eyebrow="PRIORITY QUEUE" title="Needs attention" action="View all" onAction={()=>go("Assets")}/><Alert text="HVAC annual service" detail="Due in 30 days · Heating & cooling" status="Watch" action="Request help" onClick={request}/><Alert text="Water heater maintenance" detail="Flush history incomplete · Mechanical room" status="Action soon" action="Review" onClick={()=>go("Assets")}/></section><section className="card upcoming"><Title eyebrow="NEXT 60 DAYS" title="Keep ahead of the home" action="Calendar →"/><div className="date"><time>AUG 21</time><i/><p><b>Replace HVAC filter</b><small>DIY · 10 minutes</small></p></div><div className="date"><time>SEP 14</time><i className="amber"/><p><b>Annual HVAC service</b><small>Schedule contractor</small></p></div><div className="date"><time>OCT 01</time><i className="navy"/><p><b>Winterize exterior</b><small>Seasonal checklist</small></p></div></section><section className="card activity"><Title eyebrow="LIVING RECORD" title="Recent activity" action="Open record →" onAction={()=>go("Records")}/>{[["✓","Roof inspection added","Inspection report · 12 photos · Aug 12"],["↗","Kitchen faucet replaced","Receipt and warranty saved · Jul 28"],["+","Water heater details needed","Add model and serial to strengthen record"]].map(x=><div className="activity-row" key={x[1]}><i>{x[0]}</i><p><b>{x[1]}</b><small>{x[2]}</small></p></div>)}</section></div>; }
function Metric({value,label,note}:{value:string;label:string;note:string}){return <div><b>{value}</b><span>{label}</span><small>{note}</small></div>}
function Title({eyebrow,title,action,onAction}:{eyebrow:string;title:string;action:string;onAction?:()=>void}){return <div className="title"><div><p className="eyebrow">{eyebrow}</p><h3>{title}</h3></div><button className="link" onClick={onAction}>{action}</button></div>}
function Alert({text,detail,status,action,onClick}:{text:string;detail:string;status:string;action:string;onClick:()=>void}){return <div className="alert"><i className={status==="Watch"?"orange":"amber"}/><p><b>{text}</b><small>{detail}</small></p><Status>{status}</Status><button onClick={onClick}>{action}</button></div>}

function Property({home,asset,setAsset}:{home:typeof homes[number];asset:number;setAsset:(n:number)=>void}) { return <div className="page"><section className="property-hero"><div><p className="eyebrow">DIGITAL TWIN / {home.name.toUpperCase()}</p><h2>Explore the home, not folders.</h2><p>Tap a room or system to see its equipment, evidence, and history.</p><div className="tabs"><button className="selected">Whole home</button><button>1st floor</button><button>2nd floor</button><button>Exterior</button></div></div><figure className="twin"><img src="/dollhouse.png" alt="Demo roof-off dollhouse"/><figcaption>Mirror the primary demo property from its real plan, photos, and asset locations.</figcaption></figure></section><section className="property-bottom"><div className="room-list"><p className="eyebrow">SPACES & SYSTEMS</p>{["Kitchen","Living room","Mechanical room","Primary bedroom","Roof / exterior"].map((room,i)=><button key={room} onClick={()=>setAsset(i===2?2:i===4?0:1)}><i className={i===2?"orange":""}/><b>{room}</b><small>{i===2?"1 item needs review":"Healthy"}</small><em>›</em></button>)}</div><div className="selected-asset"><p className="eyebrow">SELECTED ASSET</p><h3>{assets[asset][0]}</h3><div className="photo-box">Asset photos & evidence</div><div className="trio"><span><b>{assets[asset][3]}</b>Health</span><span><b>{assets[asset][2]}</b>Age</span><span><b>2034</b>Plan horizon</span></div><button className="primary">Open asset passport</button></div></section></div>; }

function Assets({asset,setAsset}:{asset:number;setAsset:(n:number)=>void}){const a=assets[asset];return <div className="page"><section className="asset-head"><div><p className="eyebrow">ASSET PASSPORTS</p><h2>Every important system has a record.</h2><p>Identity, condition, lifecycle, maintenance, warranty, and proof in one place.</p></div><div><b>24</b><span>assets captured</span><small>68% complete</small></div></section><section className="assets-layout"><div className="asset-list">{assets.map((row,i)=><button className={i===asset?"asset-row selected":"asset-row"} onClick={()=>setAsset(i)} key={row[0]}><i className={row[4]==="Good"?"asset-icon":"asset-icon orange"}>{row[1][0]}</i><p><b>{row[0]}</b><small>{row[1]} · {row[2]}</small></p><span className="bar"><i style={{width:`${row[3]}%`}}/><small>{row[3]} health</small></span><Status>{row[4]}</Status><em>›</em></button>)}</div><aside className="passport"><p className="eyebrow">ASSET PASSPORT</p><Status>{a[4]}</Status><h3>{a[0]}</h3><p>{a[1]} · Mechanical room</p><div className="photo-box">Equipment photo</div><div className="trio"><span><b>{a[3]}</b>Health</span><span><b>{a[2]}</b>Current age</span><span><b>8 yrs</b>Est. life left</span></div><div className="note"><b>Why this status</b><p>{a[5]}. HomeOps keeps this separate from verified records.</p></div><button className="plain">View evidence & history →</button></aside></section></div>}

function Records(){const rows=[["Aug 12, 2026","Roof inspection","12 photos · inspection report","Good"],["Jul 28, 2026","Kitchen faucet replaced","Invoice · warranty · contractor","Good"],["Mar 04, 2025","HVAC maintenance","Service record · filter replacement","Good"],["May 18, 2021","Water heater installed","Receipt missing · owner-reported date","Watch"]];return <div className="page"><section className="records-head"><div><p className="eyebrow">PERMANENT PROPERTY RECORD</p><h2>History you can prove.</h2><p>Every item stays connected to the home, asset, room, and event it supports.</p></div><div className="completeness"><b>68%</b><span>record completeness</span><i><em/></i></div></section><section className="records-layout"><div className="timeline"><p className="eyebrow">LIVING TIMELINE</p>{rows.map(r=><article key={r[0]}><time>{r[0]}</time><i/><div><p><b>{r[1]}</b><Status>{r[3]}</Status></p><small>{r[2]}</small></div></article>)}</div><aside className="evidence"><p className="eyebrow">EVIDENCE LIBRARY</p><h3>What is on file</h3>{[["▧","Inspection reports","4 files"],["▤","Receipts & invoices","8 files"],["◫","Manuals & warranties","6 files"],["⌘","Permits & public data","3 records"]].map(x=><button key={x[1]}><i>{x[0]}</i><b>{x[1]}</b><small>{x[2]}</small><em>›</em></button>)}<button className="primary">+ Add record</button></aside></section></div>}

function Service({issue}:{issue:boolean}){return <div className="page"><section className="service-hero"><p className="eyebrow">SERVICE GATEWAY</p><h2>Tell us what is wrong.<br/>HomeOps supplies the context.</h2><p>No need to know the equipment, model number, or maintenance history. Start with the symptom.</p></section><section className="service-layout"><div className="intake"><label><b>1</b> Describe the issue</label><textarea defaultValue={issue?"I need to schedule the annual HVAC service.":""} placeholder="Example: The room is warm, the system is making a sound, or I noticed water near..."/><label><b>2</b> Where is it happening?</label><div className="choices"><button className="selected">Mechanical room</button><button>Kitchen</button><button>Exterior</button><button>Not sure</button></div><label><b>3</b> Add photos or video</label><button className="upload">＋<b>Drop photos here</b><small>HomeOps attaches known asset and record context automatically.</small></button><button className="primary full">Build service request →</button></div><aside className="packet"><p className="eyebrow">CONTRACTOR PACKET PREVIEW</p><h3>What gets shared—only with your approval.</h3>{[["Known asset context","Furnace + A/C · age · service history"],["Relevant evidence","Manuals, prior work, photos, and access notes"],["Property view","Room location and digital-twin marker"]].map(x=><div key={x[0]}><i>✓</i><p><b>{x[0]}</b><small>{x[1]}</small></p></div>)}<section><b>Your record stays yours.</b><p>Share a purpose-built packet—not your entire home record.</p></section></aside></section></div>}
